{
  "openapi": "3.1.0",
  "info": {
    "title": "FastAPI",
    "version": "0.1.0"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "Root",
        "operationId": "root__get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {

                }
              }
            }
          }
        }
      }
    },
    "/api/v1/user/{userId}": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "Get User Profile",
        "operationId": "get_user_profile_api_v1_user__userId__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Userid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessResponse"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "status": "Success",
                      "data": {
                        "isDeleted": false,
                        "name": "Collins Makafui Baragbor",
                        "role": "individual",
                        "userId": "nzMn1GjJzYbJZdz0dsyiInnmLkL2",
                        "isEmployee": false,
                        "createdAt": "2026-02-02T00:47:30.222295+00:00",
                        "email": "cbaragbor@gmail.com",
                        "phoneNumber": "+233200585542",
                        "lastActive": "2026-04-22T23:27:10.607176+00:00",
                        "updatedBy": "nzMn1GjJzYbJZdz0dsyiInnmLkL2",
                        "defaultAddressId": "UerFfgOiU6kWMbKJeJpU",
                        "updatedAt": "2026-04-22T23:53:29.937242+00:00"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "value": {
                      "status": "Failed",
                      "message": "Invalid credentials."
                    }
                  },
                  "Expired Token": {
                    "value": {
                      "status": "Failed",
                      "message": "Refresh token is invalid or expired."
                    }
                  },
                  "Not authenticated": {
                    "value": {
                      "status": "Failed",
                      "message": "Not authenticated"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Access denied."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "examples": {
                  "User Not Found": {
                    "value": {
                      "status": "Failed",
                      "message": "User not found."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Failed to fetch user profile."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": [
          "Profile"
        ],
        "summary": "Update User Profile",
        "operationId": "update_user_profile_api_v1_user__userId__patch",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Userid"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserProfile"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessResponse"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "status": "Success",
                      "message": "Profile updated successfully."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "No valid fields to update": {
                    "value": {
                      "status": "Failed",
                      "message": "No valid fields to update."
                    }
                  },
                  "Invalid phone number": {
                    "value": {
                      "status": "Failed",
                      "message": "Invalid phone number."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "value": {
                      "status": "Failed",
                      "message": "Invalid credentials."
                    }
                  },
                  "Expired Token": {
                    "value": {
                      "status": "Failed",
                      "message": "Refresh token is invalid or expired."
                    }
                  },
                  "Not authenticated": {
                    "value": {
                      "status": "Failed",
                      "message": "Not authenticated"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Access denied."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "examples": {
                  "User Not Found": {
                    "value": {
                      "status": "Failed",
                      "message": "User not found."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Failed to update profile."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Profile"
        ],
        "summary": "Deactivate User",
        "operationId": "deactivate_user_api_v1_user__userId__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Userid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessResponse"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "status": "Success",
                      "message": "Account deactivated successfully."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "User already deactivated": {
                    "value": {
                      "status": "Failed",
                      "message": "User already deactivated."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "value": {
                      "status": "Failed",
                      "message": "Invalid credentials."
                    }
                  },
                  "Expired Token": {
                    "value": {
                      "status": "Failed",
                      "message": "Refresh token is invalid or expired."
                    }
                  },
                  "Not authenticated": {
                    "value": {
                      "status": "Failed",
                      "message": "Not authenticated"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "examples": {
                  "User Not Found": {
                    "value": {
                      "status": "Failed",
                      "message": "User not found."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Failed to deactivate account."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/user/{userId}/addresses": {
      "get": {
        "tags": [
          "Shipping Addresses"
        ],
        "summary": "Get Shipping Addresses",
        "operationId": "get_shipping_addresses_api_v1_user__userId__addresses_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Userid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessResponse"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "status": "Success",
                      "data": [
                        {
                          "addressId": "8ToKi8i3axNQK1JH2vXs",
                          "streetAddress": "123 Main St",
                          "ghanapostCode": "GS-0001-0001",
                          "city": "Accra",
                          "state": "Greater Accra",
                          "country": "Ghana",
                          "longitude": -0.2,
                          "latitude": 5.555555,
                          "isDefault": true,
                          "userId": "nzMn1GjJzYbJZdz0dsyiInnmLkL2",
                          "createdAt": "2026-02-02T00:47:30.222295+00:00",
                          "recipientName": "Collins Baragbor",
                          "recipientPhoneNumber": "+233200585542"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "value": {
                      "status": "Failed",
                      "message": "Invalid credentials."
                    }
                  },
                  "Expired Token": {
                    "value": {
                      "status": "Failed",
                      "message": "Refresh token is invalid or expired."
                    }
                  },
                  "Not authenticated": {
                    "value": {
                      "status": "Failed",
                      "message": "Not authenticated"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Access denied."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Failed to fetch shipping addresses."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/user/{userId}/addresses/add": {
      "post": {
        "tags": [
          "Shipping Addresses"
        ],
        "summary": "Add Shipping Address",
        "operationId": "add_shipping_address_api_v1_user__userId__addresses_add_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Userid"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddressCreate"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessResponse"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "status": "Success",
                      "message": "Shipping address added successfully.",
                      "data": {
                        "addressId": "8ToKi8i3axNQK1JH2vXs",
                        "streetAddress": "123 Main St",
                        "ghanapostCode": "GS-0001-0001",
                        "city": "Accra",
                        "state": "Greater Accra",
                        "country": "Ghana",
                        "longitude": -0.2,
                        "latitude": 5.555555,
                        "isDefault": true,
                        "userId": "nzMn1GjJzYbJZdz0dsyiInnmLkL2",
                        "createdAt": "2026-02-02T00:47:30.222295+00:00",
                        "recipientName": "Collins Baragbor",
                        "recipientPhoneNumber": "+233200585542"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "Invalid ghanapostCode": {
                    "value": {
                      "status": "Failed",
                      "message": "Invalid ghanapostCode format."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "value": {
                      "status": "Failed",
                      "message": "Invalid credentials."
                    }
                  },
                  "Expired Token": {
                    "value": {
                      "status": "Failed",
                      "message": "Refresh token is invalid or expired."
                    }
                  },
                  "Not authenticated": {
                    "value": {
                      "status": "Failed",
                      "message": "Not authenticated"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Access denied."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Failed to add shipping address."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/user/{userId}/addresses/{addressId}": {
      "patch": {
        "tags": [
          "Shipping Addresses"
        ],
        "summary": "Update Address",
        "operationId": "update_address_api_v1_user__userId__addresses__addressId__patch",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Userid"
            }
          },
          {
            "name": "addressId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Addressid"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddressUpdate"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessResponse"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "status": "Success",
                      "message": "Address updated successfully."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "Invalid ghanapostCode": {
                    "value": {
                      "status": "Failed",
                      "message": "Invalid ghanapostCode format."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "value": {
                      "status": "Failed",
                      "message": "Invalid credentials."
                    }
                  },
                  "Expired Token": {
                    "value": {
                      "status": "Failed",
                      "message": "Refresh token is invalid or expired."
                    }
                  },
                  "Not authenticated": {
                    "value": {
                      "status": "Failed",
                      "message": "Not authenticated"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Access denied."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "examples": {
                  "Address Not Found": {
                    "value": {
                      "status": "Failed",
                      "message": "Address not found."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Failed to update shipping address."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Shipping Addresses"
        ],
        "summary": "Delete Address",
        "operationId": "delete_address_api_v1_user__userId__addresses__addressId__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Userid"
            }
          },
          {
            "name": "addressId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Addressid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessResponse"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "status": "Success",
                      "message": "Address deleted successfully."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "value": {
                      "status": "Failed",
                      "message": "Invalid credentials."
                    }
                  },
                  "Expired Token": {
                    "value": {
                      "status": "Failed",
                      "message": "Refresh token is invalid or expired."
                    }
                  },
                  "Not authenticated": {
                    "value": {
                      "status": "Failed",
                      "message": "Not authenticated"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Access denied."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "examples": {
                  "Address Not Found": {
                    "value": {
                      "status": "Failed",
                      "message": "Address not found."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Failed to delete shipping address."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/user/{userId}/addresses/{addressId}/set-default": {
      "patch": {
        "tags": [
          "Shipping Addresses"
        ],
        "summary": "Set Default Address",
        "operationId": "set_default_address_api_v1_user__userId__addresses__addressId__set_default_patch",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Userid"
            }
          },
          {
            "name": "addressId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Addressid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessResponse"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "status": "Success",
                      "message": "Default address set successfully."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "value": {
                      "status": "Failed",
                      "message": "Invalid credentials."
                    }
                  },
                  "Expired Token": {
                    "value": {
                      "status": "Failed",
                      "message": "Refresh token is invalid or expired."
                    }
                  },
                  "Not authenticated": {
                    "value": {
                      "status": "Failed",
                      "message": "Not authenticated"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Access denied."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "examples": {
                  "Address Not Found": {
                    "value": {
                      "status": "Failed",
                      "message": "Address not found."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "Failed",
                  "message": "Failed to set default address."
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "AddressCreate": {
        "properties": {
          "streetAddress": {
            "type": "string",
            "title": "Streetaddress"
          },
          "ghanapostCode": {
            "type": "string",
            "title": "Ghanapostcode"
          },
          "city": {
            "type": "string",
            "title": "City"
          },
          "state": {
            "type": "string",
            "title": "State"
          },
          "country": {
            "type": "string",
            "title": "Country"
          },
          "recipientName": {
            "type": "string",
            "title": "Recipientname"
          },
          "recipientPhoneNumber": {
            "type": "string",
            "title": "Recipientphonenumber"
          },
          "longitude": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "title": "Longitude"
          },
          "latitude": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "title": "Latitude"
          },
          "isDefault": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "title": "Isdefault",
            "default": false
          }
        },
        "type": "object",
        "required": [
          "streetAddress",
          "ghanapostCode",
          "city",
          "state",
          "country",
          "recipientName",
          "recipientPhoneNumber"
        ],
        "title": "AddressCreate"
      },
      "AddressUpdate": {
        "properties": {
          "streetAddress": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Streetaddress"
          },
          "ghanapostCode": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Ghanapostcode"
          },
          "city": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "City"
          },
          "state": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "State"
          },
          "country": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Country"
          },
          "recipientName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Recipientname"
          },
          "recipientPhoneNumber": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Recipientphonenumber"
          },
          "longitude": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "title": "Longitude"
          },
          "latitude": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "title": "Latitude"
          }
        },
        "type": "object",
        "title": "AddressUpdate"
      },
      "ErrorResponse": {
        "properties": {
          "status": {
            "type": "string",
            "title": "Status"
          },
          "message": {
            "type": "string",
            "title": "Message"
          }
        },
        "type": "object",
        "required": [
          "status",
          "message"
        ],
        "title": "ErrorResponse"
      },
      "HTTPValidationError": {
        "properties": {
          "detail": {
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            },
            "type": "array",
            "title": "Detail"
          }
        },
        "type": "object",
        "title": "HTTPValidationError"
      },
      "SuccessResponse": {
        "properties": {
          "status": {
            "type": "string",
            "title": "Status"
          },
          "message": {
            "type": "string",
            "title": "Message"
          }
        },
        "type": "object",
        "required": [
          "status",
          "message"
        ],
        "title": "SuccessResponse"
      },
      "UpdateUserProfile": {
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Name"
          },
          "phoneNumber": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Phonenumber"
          },
          "email": {
            "anyOf": [
              {
                "type": "string",
                "format": "email"
              },
              {
                "type": "null"
              }
            ],
            "title": "Email"
          },
          "regNumber": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Regnumber"
          },
          "industry": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Industry"
          },
          "companyName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Companyname"
          }
        },
        "additionalProperties": false,
        "type": "object",
        "title": "UpdateUserProfile"
      },
      "ValidationError": {
        "properties": {
          "loc": {
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            },
            "type": "array",
            "title": "Location"
          },
          "msg": {
            "type": "string",
            "title": "Message"
          },
          "type": {
            "type": "string",
            "title": "Error Type"
          }
        },
        "type": "object",
        "required": [
          "loc",
          "msg",
          "type"
        ],
        "title": "ValidationError"
      }
    },
    "securitySchemes": {
      "OAuth2PasswordBearer": {
        "type": "oauth2",
        "flows": {
          "password": {
            "scopes": {

            },
            "tokenUrl": "/token"
          }
        }
      }
    }
  }
}